import type { Metadata } from "next";
import "../app/globals.css";
import MainProvider from "./provider";
import ConvexClientProvider from "@/app/ConvexClientProvider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ConvexClientProvider>
          <MainProvider>
            {children}
            <Toaster />
          </MainProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
